
before:
  hooks:
    - make test
builds:
  - dir: ./task/neo
    main: .
    id: "neo"
    binary: "optimus-neo_{{.Os}}_{{.Arch}}"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Image=ghcr.io/kushsharma/optimus-task-neo-executor
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "ghcr.io/kushsharma/optimus-task-neo-executor:latest"
    - "ghcr.io/kushsharma/optimus-task-neo-executor:{{ .Version }}"
    dockerfile: ./task/neo/executor/Dockerfile
    extra_files:
    - task/neo/executor

  # optional
  # -
  #   goos: linux
  #   goarch: amd64
  #   image_templates:
  #   - "ghcr.io/kushsharma/optimus-task-neo:latest"
  #   - "ghcr.io/kushsharma/optimus-task-neo:{{ .Version }}"
  #   dockerfile: ./task/neo/example.Dockerfile
  #   extra_files:
  #   - task/neo/example.entrypoint.sh
  #   build_flag_templates:
  #   - "--build-arg=OPTIMUS_RELEASE_URL=https://github.com/odpf/optimus/releases/download/v0.0.1-rc.2/optimus_0.0.1-rc.2_linux_x86_64.tar.gz"

brews:
  - name: optimus-plugins-kush
    install: |
      bin.install Dir["optimus-*"]
    tap:
      owner: kushsharma
      name: homebrew-taps
    license: "Apache 2.0"
    description: "Optimus plugins - [Optimus Near earth orbit tracker]"
    commit_author:
      name: Kush Sharma
      email: 3647166+kushsharma@users.noreply.github.com